channels:
  - conda-forge
  - defaults
dependencies:
  - dill=0.2.9
  - nbsphinx=0.4.3
  - notebook=5.7.8
  - numpy=1.16.3
  - pandas=0.24.2
  - pip=19.1.1
  - python=3.7.3
  - scipy=1.2.1
  - sphinx=2.2.0
  - matplotlib
  - recommonmark=0.5.0
  - wand
  - pip:
      - ./.
